name: paraphrase
description: A dart AST tool that simplify the dart analyzer struct and collect all the AST nodes as result.
version: 0.2.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  analyzer: ^6.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.1
